// <auto-generated />
using AccountDeduplication.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccountDeduplication.DAL.Migrations
{
    [DbContext(typeof(AccountDedupeDb))]
    [Migration("20250604022639_Migrate")]
    partial class Migrate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("AccountDeduplication.DAL.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(18)
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingState")
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingStreet")
                        .HasColumnType("TEXT");

                    b.Property<string>("Grouping")
                        .HasColumnType("TEXT");

                    b.Property<string>("NPI")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfRoles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OtherOrgName")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordTypeName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingState")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingStreet")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("AccountDeduplication.DAL.MatchRate", b =>
                {
                    b.Property<string>("AccountId1")
                        .HasMaxLength(18)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("AccountId2")
                        .HasMaxLength(18)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<int>("Account1RoleCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Account2RoleCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("BillingStreetMatch")
                        .HasColumnType("REAL");

                    b.Property<double>("NameMatch")
                        .HasColumnType("REAL");

                    b.Property<double>("OtherNameMatch")
                        .HasColumnType("REAL");

                    b.Property<double>("ShippingAddressMatch")
                        .HasColumnType("REAL");

                    b.HasKey("AccountId1", "AccountId2");

                    b.ToTable("MatchRates");
                });
#pragma warning restore 612, 618
        }
    }
}
