// <auto-generated />
using System;
using AccountDeduplication.DAL.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccountDeduplication.DAL.EF.Migrations
{
    [DbContext(typeof(AccountDedupeDb))]
    [Migration("20250623193309_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("AccountDeduplication.DAL.Models.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(18)
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingHouseNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingPostalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingState")
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingStreet")
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingStreetNormalized")
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingStreetRaw")
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingUnit")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupingCityState")
                        .HasColumnType("TEXT");

                    b.Property<string>("NPI")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfRoles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OtherOrgName")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordTypeName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingHouseNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingPostalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingState")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingStreet")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingStreetNormalized")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingStreetRaw")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingUnit")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BillingCity");

                    b.HasIndex("GroupingCityState");

                    b.HasIndex("ShippingCity");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("AccountDeduplication.DAL.Models.GroupPair", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Phase")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupAccountId")
                        .HasColumnType("TEXT");

                    b.Property<double>("MatchPercentage")
                        .HasColumnType("REAL");

                    b.HasKey("AccountId", "Phase");

                    b.HasIndex("GroupAccountId");

                    b.ToTable("GroupPairs");
                });

            modelBuilder.Entity("AccountDeduplication.DAL.Models.MatchRate", b =>
                {
                    b.Property<string>("AccountId1")
                        .HasMaxLength(18)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("AccountId2")
                        .HasMaxLength(18)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<int>("Account1RoleCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Account2RoleCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("BillingStreetMatch")
                        .HasColumnType("REAL");

                    b.Property<double>("NameMatch")
                        .HasColumnType("REAL");

                    b.Property<double>("OtherNameMatch")
                        .HasColumnType("REAL");

                    b.Property<double>("ShippingAddressMatch")
                        .HasColumnType("REAL");

                    b.HasKey("AccountId1", "AccountId2");

                    b.HasIndex("AccountId2");

                    b.ToTable("MatchRates");
                });

            modelBuilder.Entity("AccountDeduplication.DAL.Models.ProcessingStatus", b =>
                {
                    b.Property<string>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccountsInGroup")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("ProcessingTime")
                        .HasColumnType("TEXT");

                    b.HasKey("GroupId");

                    b.ToTable("ProcessingStatuses");
                });

            modelBuilder.Entity("AccountDeduplication.DAL.Models.GroupPair", b =>
                {
                    b.HasOne("AccountDeduplication.DAL.Models.Account", "Account")
                        .WithMany("GroupPairs")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccountDeduplication.DAL.Models.Account", "GroupAccount")
                        .WithMany()
                        .HasForeignKey("GroupAccountId");

                    b.Navigation("Account");

                    b.Navigation("GroupAccount");
                });

            modelBuilder.Entity("AccountDeduplication.DAL.Models.MatchRate", b =>
                {
                    b.HasOne("AccountDeduplication.DAL.Models.Account", "Account1")
                        .WithMany()
                        .HasForeignKey("AccountId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccountDeduplication.DAL.Models.Account", "Account2")
                        .WithMany()
                        .HasForeignKey("AccountId2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account1");

                    b.Navigation("Account2");
                });

            modelBuilder.Entity("AccountDeduplication.DAL.Models.Account", b =>
                {
                    b.Navigation("GroupPairs");
                });
#pragma warning restore 612, 618
        }
    }
}
