// <auto-generated />
using System;
using AccountDeduplication.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccountDeduplication.DAL.Migrations
{
    [DbContext(typeof(AccountDedupeDb))]
    partial class AccountDedupeDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("AccountDeduplication.DAL.MatchRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Account1RoleCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Account2RoleCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId1")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId2")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("TEXT");

                    b.Property<double>("BillingStreetMatch")
                        .HasColumnType("REAL");

                    b.Property<double>("NameMatch")
                        .HasColumnType("REAL");

                    b.Property<double>("OtherNameMatch")
                        .HasColumnType("REAL");

                    b.Property<double>("ShippingAddressMatch")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AccountId1");

                    b.HasIndex("AccountId2");

                    b.ToTable("MatchRates");
                });
#pragma warning restore 612, 618
        }
    }
}
