namespace AccountDeduplication.LoadDatabase;

public static class CityStateListMap
{
    public static readonly Dictionary<string, string> StateMap = new(StringComparer.OrdinalIgnoreCase)
    {
        { "alabama", "al" }, { "al", "al" },
        { "alaska", "ak" }, { "ak", "ak" },
        { "arizona", "az" }, { "az", "az" },
        { "arkansas", "ar" }, { "ar", "ar" },
        { "california", "ca" }, { "ca", "ca" },
        { "colorado", "co" }, { "co", "co" },
        { "connecticut", "ct" }, { "ct", "ct" },
        { "delaware", "de" }, { "de", "de" },
        { "florida", "fl" }, { "fl", "fl" },
        { "georgia", "ga" }, { "ga", "ga" },
        { "hawaii", "hi" }, { "hi", "hi" },
        { "idaho", "id" }, { "id", "id" },
        { "illinois", "il" }, { "il", "il" },
        { "indiana", "in" }, { "in", "in" },
        { "iowa", "ia" }, { "ia", "ia" },
        { "kansas", "ks" }, { "ks", "ks" },
        { "kentucky", "ky" }, { "ky", "ky" },
        { "louisiana", "la" }, { "la", "la" },
        { "maine", "me" }, { "me", "me" },
        { "maryland", "md" }, { "md", "md" },
        { "massachusetts", "ma" }, { "ma", "ma" },
        { "michigan", "mi" }, { "mi", "mi" },
        { "minnesota", "mn" }, { "mn", "mn" },
        { "mississippi", "ms" }, { "ms", "ms" },
        { "missouri", "mo" }, { "mo", "mo" },
        { "montana", "mt" }, { "mt", "mt" },
        { "nebraska", "ne" }, { "ne", "ne" },
        { "nevada", "nv" }, { "nv", "nv" },
        { "new hampshire", "nh" }, { "nh", "nh" },
        { "new jersey", "nj" }, { "nj", "nj" },
        { "new mexico", "nm" }, { "nm", "nm" },
        { "new york", "ny" }, { "ny", "ny" },
        { "north carolina", "nc" }, { "nc", "nc" },
        { "north dakota", "nd" }, { "nd", "nd" },
        { "ohio", "oh" }, { "oh", "oh" },
        { "oklahoma", "ok" }, { "ok", "ok" },
        { "oregon", "or" }, { "or", "or" },
        { "pennsylvania", "pa" }, { "pa", "pa" },
        { "rhode island", "ri" }, { "ri", "ri" },
        { "south carolina", "sc" }, { "sc", "sc" },
        { "south dakota", "sd" }, { "sd", "sd" },
        { "tennessee", "tn" }, { "tn", "tn" },
        { "texas", "tx" }, { "tx", "tx" },
        { "utah", "ut" }, { "ut", "ut" },
        { "vermont", "vt" }, { "vt", "vt" },
        { "virginia", "va" }, { "va", "va" },
        { "washington", "wa" }, { "wa", "wa" },
        { "west virginia", "wv" }, { "wv", "wv" },
        { "wisconsin", "wi" }, { "wi", "wi" },
        { "wyoming", "wy" }, { "wy", "wy" },
        { "district of columbia", "dc" }, { "dc", "dc" },
        { "puerto rico", "pr"}, { "pr", "pr"}
    };

    public static readonly string[] LowercasedStateNames =
    [
        "alabama",
        "alaska",
        "arizona",
        "arkansas",
        "california",
        "colorado",
        "connecticut",
        "delaware",
        "florida",
        "georgia",
        "hawaii",
        "idaho",
        "illinois",
        "indiana",
        "iowa",
        "kansas",
        "kentucky",
        "louisiana",
        "maine",
        "maryland",
        "massachusetts",
        "michigan",
        "minnesota",
        "mississippi",
        "missouri",
        "montana",
        "nebraska",
        "nevada",
        "new hampshire",
        "new jersey",
        "new mexico",
        "new york",
        "north carolina",
        "north dakota",
        "ohio",
        "oklahoma",
        "oregon",
        "pennsylvania",
        "puerto rico",
        "rhode island",
        "south carolina",
        "south dakota",
        "tennessee",
        "texas",
        "utah",
        "vermont",
        "virginia",
        "washington",
        "west virginia",
        "wisconsin",
        "wyoming",
        "district of columbia"
    ];
}